name: Leer JSON

on:
  [push]

jobs: 
  print-json: 
    name: Imprimir JSON
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      
      - name: Mostrar Contenido JSON
        run: cat planes_sedes.json >> $GITHUB_STEP_SUMMARY